name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - run: npm ci --ignore-scripts --legacy-peer-deps
      - run: npm run build
      
      - name: Get version
        id: version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Create archive
        run: |
          cd dist && tar -czf ../n8n-opencode-node-v${{ steps.version.outputs.VERSION }}.tar.gz . && cd ..
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: n8n-opencode-node-v${{ steps.version.outputs.VERSION }}.tar.gz
          tag_name: v${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
        if: startsWith(github.ref, 'refs/heads/main')
